### ISSUE TITLE
Incompatible with mod Immersive Portals

### ISSUE THREAD

**Issue by linzexin022** [Levoment/SuperAxes#7]
Minecraft version: 1.16.4
Super Axes version: 2.0.9
Immersive Portals version: 0.55

`[11:59:09] [Thread-139/INFO]: [STDERR]: java.lang.IllegalArgumentException: The validated expression is false
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at org.apache.commons.lang3.Validate.isTrue(Validate.java:183)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at com.qouteall.immersive_portals.network.CommonNetwork.withForceRedirect(CommonNetwork.java:24)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at net.minecraft.class_3898$class_3208.updateEntityTrackingStatus(class_3898.java:1956)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at net.minecraft.class_3898$class_3208.method_18729(class_3898.java:1912)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at net.minecraft.class_3898.method_18701(class_3898.java:1020)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at net.minecraft.class_3215.method_18755(class_3215.java:477)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at net.minecraft.class_3218.method_18778(class_3218.java:933)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at net.minecraft.class_3218.method_14175(class_3218.java:835)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at net.minecraft.class_3218.method_8649(class_3218.java:765)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at net.minecraft.class_1264.method_5449(class_1264.java:52)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at com.github.levoment.superaxes.Items.SuperAxeItem.lambda$mineBlockWithLootContext$2(SuperAxeItem.java:96)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at java.util.ArrayList.forEach(ArrayList.java:1259)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at com.github.levoment.superaxes.Items.SuperAxeItem.mineBlockWithLootContext(SuperAxeItem.java:94)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at com.github.levoment.superaxes.TreeChopper.breakLogs(TreeChopper.java:286)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at com.github.levoment.superaxes.TreeChopper.parallelTraverseTreeAndBreakBlocks(TreeChopper.java:221)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at com.github.levoment.superaxes.TreeChopper.cutTree(TreeChopper.java:66)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at com.github.levoment.superaxes.Items.SuperAxeItem.lambda$canMine$0(SuperAxeItem.java:59)
[11:59:09] [Thread-139/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)`

**Comment by Levoment** [comment]
Hi

Thanks for the issue.

I honestly don't know how to make it compatible since SuperAxes uses parallelization to scan for tree logs. While parallelization can be removed to eliminate the thread created to scan for logs, it would cause the game to completely freeze while the blocks to break are being scanned.

**Comment by Levoment** [comment]
The fix for this problem can be found on release [2.0.11](https://github.com/Levoment/SuperAxes/releases/tag/refs%2Fheads%2Frelease%2F2.0.11)
Commit: [e2c63fba5b00b9086a3026b950d815343f9b7739](https://github.com/Levoment/SuperAxes/commit/e2c63fba5b00b9086a3026b950d815343f9b7739)
